% CASE STUDIES IN EXPERIMENTAL PSYCHOLOGY: DEMENTIA DATASET
% Matlab script for the extraction of mean alpha wave power per channel per participant
% The preprocessed data is available in the folder 'original_data', or can be downloaded here from
% OpenNeuro, in the folder 'derivatives': https://openneuro.org/datasets/ds004504/versions/1.0.5

% Add EEGLAB to the MATLAB path
eeglab_path = 'path_to_eeglab_folder';  % Replace with the actual path to your EEGLAB folder
addpath(eeglab_path);
eeglab;

% Define dataset filenames and paths
dataset_files = {
    'sub-001_task-eyesclosed_eeg.set', ...
    'sub-002_task-eyesclosed_eeg.set', ...
    'sub-003_task-eyesclosed_eeg.set', ...
    'sub-004_task-eyesclosed_eeg.set', ...
    'sub-005_task-eyesclosed_eeg.set', ...
    'sub-006_task-eyesclosed_eeg.set', ...
    'sub-007_task-eyesclosed_eeg.set', ...
    'sub-008_task-eyesclosed_eeg.set', ...
    'sub-009_task-eyesclosed_eeg.set', ...
    'sub-010_task-eyesclosed_eeg.set', ...
    'sub-011_task-eyesclosed_eeg.set', ...
    'sub-012_task-eyesclosed_eeg.set', ...
    'sub-013_task-eyesclosed_eeg.set', ...
    'sub-014_task-eyesclosed_eeg.set', ...
    'sub-015_task-eyesclosed_eeg.set', ...
    'sub-016_task-eyesclosed_eeg.set', ...
    'sub-017_task-eyesclosed_eeg.set', ...
    'sub-018_task-eyesclosed_eeg.set', ...
    'sub-019_task-eyesclosed_eeg.set', ...
    'sub-020_task-eyesclosed_eeg.set', ...
    'sub-021_task-eyesclosed_eeg.set', ...
    'sub-022_task-eyesclosed_eeg.set', ...
    'sub-023_task-eyesclosed_eeg.set', ...
    'sub-024_task-eyesclosed_eeg.set', ...
    'sub-025_task-eyesclosed_eeg.set', ...
    'sub-026_task-eyesclosed_eeg.set', ...
    'sub-027_task-eyesclosed_eeg.set', ...
    'sub-028_task-eyesclosed_eeg.set', ...
    'sub-029_task-eyesclosed_eeg.set', ...
    'sub-030_task-eyesclosed_eeg.set', ...
    'sub-031_task-eyesclosed_eeg.set', ...
    'sub-032_task-eyesclosed_eeg.set', ...
    'sub-033_task-eyesclosed_eeg.set', ...
    'sub-034_task-eyesclosed_eeg.set', ...
    'sub-035_task-eyesclosed_eeg.set', ...
    'sub-036_task-eyesclosed_eeg.set', ...
    'sub-037_task-eyesclosed_eeg.set', ...
    'sub-038_task-eyesclosed_eeg.set', ...
    'sub-039_task-eyesclosed_eeg.set', ...
    'sub-040_task-eyesclosed_eeg.set', ...
    'sub-041_task-eyesclosed_eeg.set', ...
    'sub-042_task-eyesclosed_eeg.set', ...
    'sub-043_task-eyesclosed_eeg.set', ...
    'sub-044_task-eyesclosed_eeg.set', ...
    'sub-045_task-eyesclosed_eeg.set', ...
    'sub-046_task-eyesclosed_eeg.set', ...
    'sub-047_task-eyesclosed_eeg.set', ...
    'sub-048_task-eyesclosed_eeg.set', ...
    'sub-049_task-eyesclosed_eeg.set', ...
    'sub-050_task-eyesclosed_eeg.set', ...
    'sub-051_task-eyesclosed_eeg.set', ...
    'sub-052_task-eyesclosed_eeg.set', ...
    'sub-053_task-eyesclosed_eeg.set', ...
    'sub-054_task-eyesclosed_eeg.set', ...
    'sub-055_task-eyesclosed_eeg.set', ...
    'sub-056_task-eyesclosed_eeg.set', ...
    'sub-057_task-eyesclosed_eeg.set', ...
    'sub-058_task-eyesclosed_eeg.set', ...
    'sub-059_task-eyesclosed_eeg.set', ...
    'sub-060_task-eyesclosed_eeg.set', ...
    'sub-061_task-eyesclosed_eeg.set', ...
    'sub-062_task-eyesclosed_eeg.set', ...
    'sub-063_task-eyesclosed_eeg.set', ...
    'sub-064_task-eyesclosed_eeg.set', ...
    'sub-065_task-eyesclosed_eeg.set', ...
    'sub-066_task-eyesclosed_eeg.set', ...
    'sub-067_task-eyesclosed_eeg.set', ...
    'sub-068_task-eyesclosed_eeg.set', ...
    'sub-069_task-eyesclosed_eeg.set', ...
    'sub-070_task-eyesclosed_eeg.set', ...
    'sub-071_task-eyesclosed_eeg.set', ...
    'sub-072_task-eyesclosed_eeg.set', ...
    'sub-073_task-eyesclosed_eeg.set', ...
    'sub-074_task-eyesclosed_eeg.set', ...
    'sub-075_task-eyesclosed_eeg.set', ...
    'sub-076_task-eyesclosed_eeg.set', ...
    'sub-077_task-eyesclosed_eeg.set', ...
    'sub-078_task-eyesclosed_eeg.set', ...
    'sub-079_task-eyesclosed_eeg.set', ...
    'sub-080_task-eyesclosed_eeg.set', ...
    'sub-081_task-eyesclosed_eeg.set', ...
    'sub-082_task-eyesclosed_eeg.set', ...
    'sub-083_task-eyesclosed_eeg.set', ...
    'sub-084_task-eyesclosed_eeg.set', ...
    'sub-085_task-eyesclosed_eeg.set', ...
    'sub-086_task-eyesclosed_eeg.set', ...
    'sub-087_task-eyesclosed_eeg.set', ...
    'sub-088_task-eyesclosed_eeg.set', 
};
dataset_folder = 'Path_to_folder_with_dataset_files';  % Replace this folder path with you own folder path

% Select which EEG channels and which frequency range
% we chose to analyse alpha waves
eeg_channels = 1:19;  % Replace with the indices of EEG channels of interest. -> we analyse all 19 channels available in the data
alpha_freq_range = [8, 12.5];  % Replace with the desired frequency range (in Hz) -> we analyse alpha and therefore look at the range 8 - 12.5 Hz

% Perform spectral density analysis to have values for statistical analysis
window_length = 2;  % Replace with the desired window length in seconds -> two seconds is default for alpha, we had no reason to change this
window_overlap = 0.5;  % Replace with the desired window overlap (0.5 = 50% overlap) -> again, we kept the default

% loop over the datasets of the participants
for dataset_idx = 1:numel(dataset_files)
    dataset_file = dataset_files{dataset_idx};
    dataset_path = fullfile(dataset_folder, dataset_file);

    % Load preprocessed EEG dataset
    EEG = pop_loadset('filename', dataset_file, 'filepath', dataset_folder);

    spectra = [];  % preparation to be able to store spectral density values
    mean_psd_values = [];  % preparation to store mean PSD values

    % Iterate over each EEG channel (19 in this case)
    for i = 1:numel(eeg_channels)
        eeg_data = EEG.data(eeg_channels(i), :);

        % Calculate spectral density using the Welch's method 
        [psd, freq] = pwelch(eeg_data, hamming(nfft), noverlap, nfft, EEG.srate);

        % Filter the PSD for the other waves out and only keep the alpha
        alpha_indices = (freq >= alpha_freq_range(1) & freq <= alpha_freq_range(2));
        alpha_psd = psd(alpha_indices);

        % Store the alpha spectral density for the current channel
        % and current dataset
        spectra = [spectra, alpha_psd'];  % Append the PSD values for the current channel

        % Calculate mean value of PSD for the current channel
        % and current dataset
        mean_psd = mean(alpha_psd);
        mean_psd_values = [mean_psd_values, mean_psd];
    end

    % Calculate standard deviation
    sd = std(mean_psd_values);

    % Define outlier threshold
    threshold = 2 * sd;

    % Remove outliers based on the treshold defined above
    mean_psd_values = mean_psd_values(mean_psd_values >= mean(mean_psd_values) - threshold & mean_psd_values <= mean(mean_psd_values) + threshold);

    % Save mean PSD values to a file
    output_filename = ['mean_psd_values_', num2str(dataset_idx, '%03d'), '.txt'];  % Replace with your desired output file name
    output_filepath = fullfile('Path_to_output_folder', output_filename);  % Replace with your desired output file path

   % Write mean PSD values to the file
    fid = fopen(output_filepath, 'w');
    for i = 1:min(numel(eeg_channels), numel(mean_psd_values))
        fprintf(fid, 'Channel%d: %.4f\n', eeg_channels(i), mean_psd_values(i));
    end
    fclose(fid);
end

% Remove EEGLAB from the MATLAB path to clean up my MATLAB folder
rmpath(eeglab_path);
